"""initial schema

Revision ID: 136395ba8309
Revises: 
Create Date: 2026-04-02 00:02:50.785766

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '136395ba8309'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('scoring_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('dimension', sa.Enum('security', 'feasibility', 'cost', 'value', name='evaluationdimension'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'dimension', name='uq_scoring_config_tenant_dimension')
    )
    op.create_index(op.f('ix_scoring_configs_tenant_id'), 'scoring_configs', ['tenant_id'], unique=False)
    op.create_table('use_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('stakeholders', sa.Text(), nullable=False),
    sa.Column('available_data', sa.Text(), nullable=False),
    sa.Column('expected_outcome', sa.Text(), nullable=False),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', 'critical', name='urgency'), nullable=False),
    sa.Column('status', sa.Enum('new', 'evaluating', 'scored', 'business_case', 'review', 'approved', 'rejected', 'archived', name='usecasestatus'), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_use_cases_status'), 'use_cases', ['status'], unique=False)
    op.create_index(op.f('ix_use_cases_tenant_id'), 'use_cases', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('roles', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    op.create_table('business_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('use_case_id', sa.String(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('problem_and_opportunity', sa.Text(), nullable=False),
    sa.Column('proposed_solution', sa.Text(), nullable=False),
    sa.Column('cost_benefit_analysis', sa.Text(), nullable=False),
    sa.Column('risks_and_mitigations', sa.Text(), nullable=False),
    sa.Column('timeline', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Enum('go', 'no_go', 'conditional', name='businesscaserecommendation'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'critic_review', 'pending_human', 'approved', 'rejected', name='businesscasestatus'), nullable=False),
    sa.Column('langgraph_thread_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['use_case_id'], ['use_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_cases_use_case_id'), 'business_cases', ['use_case_id'], unique=True)
    op.create_table('evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('use_case_id', sa.String(), nullable=False),
    sa.Column('dimension', sa.Enum('security', 'feasibility', 'cost', 'value', name='evaluationdimension'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['use_case_id'], ['use_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('use_case_id', 'dimension', name='uq_evaluation_use_case_dimension')
    )
    op.create_index(op.f('ix_evaluations_use_case_id'), 'evaluations', ['use_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_use_case_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_business_cases_use_case_id'), table_name='business_cases')
    op.drop_table('business_cases')
    op.drop_table('users')
    op.drop_index(op.f('ix_use_cases_tenant_id'), table_name='use_cases')
    op.drop_index(op.f('ix_use_cases_status'), table_name='use_cases')
    op.drop_table('use_cases')
    op.drop_index(op.f('ix_scoring_configs_tenant_id'), table_name='scoring_configs')
    op.drop_table('scoring_configs')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
