#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# deploy.sh  – Terraform apply and auto-generate .env
#
# Usage:
#   cd infra/terraform
#   cp terraform.tfvars.example terraform.tfvars   # fill in subscription_id
#   ../../infra/deploy.sh
#
# What it does:
#   1. terraform init + apply inside infra/terraform/
#   2. Reads outputs and writes the root .env file
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${SCRIPT_DIR}/terraform"
ENV_FILE="${SCRIPT_DIR}/../.env"

# ── 1. Ensure terraform.tfvars exists ────────────────────────────────────────
if [[ ! -f "${TF_DIR}/terraform.tfvars" ]]; then
  echo "ERROR: terraform.tfvars not found."
  echo "Run:  cp ${TF_DIR}/terraform.tfvars.example ${TF_DIR}/terraform.tfvars"
  echo "Then edit ${TF_DIR}/terraform.tfvars and set subscription_id."
  exit 1
fi

# ── 2. Init + Apply ──────────────────────────────────────────────────────────
echo "▶ Running terraform init…"
terraform -chdir="${TF_DIR}" init -upgrade

echo "▶ Running terraform apply…"
terraform -chdir="${TF_DIR}" apply -auto-approve

# ── 3. Read sensitive outputs ─────────────────────────────────────────────────
echo "▶ Reading Terraform outputs…"

tf_output() {
  terraform -chdir="${TF_DIR}" output -raw "$1" 2>/dev/null || echo ""
}

OPENAI_ENDPOINT=$(tf_output openai_endpoint)
OPENAI_API_KEY=$(tf_output openai_api_key)
SEARCH_ENDPOINT=$(tf_output search_endpoint)
SEARCH_ADMIN_KEY=$(tf_output search_admin_key)
DATABASE_URL=$(tf_output database_url)
AZURE_AD_TENANT_ID=$(tf_output azure_ad_tenant_id)
AZURE_AD_CLIENT_ID=$(tf_output azure_ad_client_id)
AZURE_AD_AUDIENCE=$(tf_output azure_ad_audience)

# ── 4. Write .env ─────────────────────────────────────────────────────────────
echo "▶ Writing ${ENV_FILE}…"

cat > "${ENV_FILE}" <<EOF
# ─── Auto-generated by infra/deploy.sh – DO NOT COMMIT ────────────────────
# Run: infra/deploy.sh  to regenerate after infrastructure changes

# ── Application ──
APP_ENV=development
APP_DEBUG=true
APP_HOST=0.0.0.0
APP_PORT=8000

# ── Database (Azure PostgreSQL Flexible Server) ──
DATABASE_URL=${DATABASE_URL}
DATABASE_POOL_SIZE=10

# ── Azure AI Foundry ──
AZURE_OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
AZURE_OPENAI_API_KEY=${OPENAI_API_KEY}
AZURE_OPENAI_API_VERSION=2024-12-01-preview
AZURE_OPENAI_GPT4O_DEPLOYMENT=gpt-4o
AZURE_OPENAI_O3MINI_DEPLOYMENT=o3-mini

# ── Azure AI Search ──
AZURE_SEARCH_ENDPOINT=${SEARCH_ENDPOINT}
AZURE_SEARCH_ADMIN_KEY=${SEARCH_ADMIN_KEY}
AZURE_SEARCH_INDEX_PREFIX=portfolio

# ── Microsoft Entra ID (Auth) ──
AZURE_AD_TENANT_ID=${AZURE_AD_TENANT_ID}
AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID}
AZURE_AD_AUDIENCE=${AZURE_AD_AUDIENCE}

# ── LangSmith (Optional – add your key manually) ──
LANGSMITH_API_KEY=
LANGSMITH_PROJECT=ai-portfolio-manager
LANGCHAIN_TRACING_V2=false

# ── OpenTelemetry ──
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
OTEL_SERVICE_NAME=ai-portfolio-manager

# ── Frontend ──
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_COPILOTKIT_URL=/api/copilotkit

# ── Dev mode (set to false when testing full auth flow) ──
DEV_AUTH_BYPASS=true
DEV_TENANT_ID=dev-tenant-001
EOF

echo ""
echo "✅  Infrastructure deployed and .env written to: ${ENV_FILE}"
echo ""
echo "Next steps:"
echo "  1. Restart your backend:  make backend"
echo "  2. Run DB migrations:     make migrate"
echo "  3. Start the app:         make dev"
echo ""
echo "⚠️   Don't forget to add .env to .gitignore (it contains secrets)!"
